---
- name: Ensure that rundeck_admin_credentials has been set
  ansible.builtin.assert:
    that: (rundeck_admin_credentials != "")
    fail_msg: please set rundeck_admin_credentials
    success_msg: rundeck_admin_credentials has been set

- name: Parse rundeck_admin_credentials
  ansible.builtin.set_fact:
    rundeck_admin_credential_parts: '{{ rundeck_admin_credentials | split(":") }}'

- name: Generate credential facts
  ansible.builtin.set_fact:
    rundeck_admin_token: '{{ rundeck_admin_credential_parts | first }}'
    rundeck_admin_username: '{{ rundeck_admin_credential_parts | first }}'
    rundeck_admin_password: '{{ rundeck_admin_credential_parts | difference(rundeck_admin_credential_parts | first) | join("") }}'
    rundeck_admin_use_token: '{{ rundeck_admin_credential_parts | length == 1 }}'
    rundeck_admin_is_default: '{{ rundeck_admin_credentials == "admin:admin" }}'
...
