---
- name: Check admin credentials
  ansible.builtin.import_role:
    name: rundeck
    tasks_from: admin-credentials
  delegate_to: localhost
  run_once: true

- block:
    - name: Pause to confirm updating the admin password
      ansible.builtin.pause:
        echo: no
        prompt: Enter the new admin password, the inventory will be updated
      register: rundeck_admin_set_password_question

    - name: Load the inventory
      ansible.builtin.set_fact:
        inventory_data: '{{ lookup("ansible.builtin.file", inventory_file) | from_yaml }}'

    - name: Update rundeck_admin_credentials
      ansible.builtin.set_fact:
        rundeck_admin_password_new: '{{ rundeck_admin_set_password_question.user_input }}'
        inventory_data_patch: '
           {
            "all": {
              "hosts": {
                "{{ inventory_hostname }}": {
                  "rundeck_admin_credentials": "{{ rundeck_admin_username }}:{{ rundeck_admin_set_password_question.user_input }}"
                }
              }
            }
          }'

    - name: Patch inventory data
      ansible.builtin.set_fact:
        inventory_data_patched: '{{ inventory_data | combine(inventory_data_patch|from_json, recursive=True) }}'

    - name: Update the admin account in Rundeck
      ansible.builtin.blockinfile:
        path: '{{ rundeck_container_realm_file }}'
        block: |
          admin: {{ rundeck_admin_set_password_question.user_input }},user,admin
        marker: '# {mark} Managed by Ansible'
      become: yes
      tags:
        - sudo

    - name: Save the updated inventory
      ansible.builtin.copy:
        content: '{{ inventory_data_patched | to_nice_yaml }}'
        dest: '{{ item }}'
        backup: true
      loop:
        - '{{ inventory_file }}'
        - '/tmp/{{ inventory_file | basename }}'

    - name: Pause to inform the user about the copy of the inventory
      ansible.builtin.pause:
        echo: no
        prompt: "A copy of your updated inventory has been saved to /tmp/{{ inventory_file | basename }}. If you were using a custom inventory to begin with then your inventory has been updated to save the new admin password"
  
  when: (rundeck_admin_is_default | bool) and (rundeck_admin_set_password | bool)
  no_log: false
