---
- name: Ensure user bin directory exists
  ansible.builtin.file:
    path: '{{ rundeck_cli_user_bin_dir }}'
    state: directory

- name: Extract Rundeck CLI tarball
  ansible.builtin.unarchive:
    src: '{{ rundeck_cli_tarball_name }}'
    dest: '{{ rundeck_cli_user_bin_dir }}'

# line: "alias rd='podman run --rm -it --entrypoint '["java", "-jar", "/app/{{ rundeck_cli_tarball | basename }}.jar"]' -v {{ rundeck_cli_user_bin_dir }}/{{ rundeck_cli_tarball | basename }}.jar:/app/{{ rundeck_cli_user_bin_dir }}/{{ rundeck_cli_tarball | basename }}.jar:z rundeck/rundeck:{{ rundeck_version }}'
- name: Add alias for Rundeck CLI
  ansible.builtin.lineinfile:
    path: '{{ ansible_env.HOME }}/.bashrc'
    create: yes
    line: "alias rd=\"podman run --rm -it --entrypoint='[\\\"java\\\", \\\"-jar\\\", \\\"/app/{{ rundeck_cli_filename }}\\\"]' -v {{ rundeck_cli_user_bin_dir }}/{{ rundeck_cli_filename }}:/app/{{ rundeck_cli_filename }}:z {{ rundeck_container_image_repo }}/rundeck:{{ rundeck_version }}\""
    owner: '{{ ansible_env.USER }}'
    mode: u=rw,g=r,o=
...
