- name: Current Alert
  ansible.builtin.debug:
    msg: "{{ pmm_alert_item.name }}"

- name: Set Alert Filter
  ansible.builtin.set_fact:
    pmm_alerting_filters: "{% if pmm_alert_item.name is defined and pmm_alert_item.name in pmm_alert_filters %}{{ pmm_alert_filters[pmm_alert_item.name][\"filters\"] | default([])}}{% else %}[]{% endif %}"

- name: Create alerts
  ansible.builtin.uri:
    url: '{{ pmm_server_uri }}{{ pmm_api_alerting_rules_create }}'
    method: POST
    user: '{{ pmm_api_credentials[0] }}'
    password: '{{ pmm_api_credentials[1] }}'
    body: |
          {
            "custom_labels": {},
            "severity": "SEVERITY_{{ pmm_alert_item.severity | upper}}",
            "template_name": "{{ pmm_alert_item.name }}",
            "name": "{{ pmm_alert_item.name }}",
            "params": [],
            "filters": {{ pmm_alerting_filters }},
            "group": "default-alert-group",
            "folder_uid": '{{ pmm_alerting_folder_uid }}'
          }
    force_basic_auth: yes
    status_code:
      - 200
      - 409
    body_format: json
    validate_certs: '{{ pmm_server_insecure }}'
  when: pmm_get_alert_rules == "" or (pmm_alert_item.name is defined and pmm_alert_item.name not in pmm_existing_alert_rules)



