---
- name: Prepare payload
  ansible.builtin.set_fact:
    pmm_payload: '{{ pmm_payload_base | combine(pmm_payload_add_mysql_base, pmm_payload_add_mysql) }}'

- name: Add MySQL
  ansible.builtin.include_tasks: client-api.yaml
  vars:
    pmm_service: MySQL
  when: pmm_agent_running_mysqld_exporter | length == 0
...
