---
- name: Prepare payload
  ansible.builtin.set_fact:
    pmm_payload: '{{ pmm_payload_base | combine(pmm_payload_add_proxysql_base, pmm_payload_add_proxysql) }}'

- name: Add ProxySQL
  ansible.builtin.include_tasks: client-api.yaml
  vars:
    pmm_service: ProxySQL
  when: pmm_agent_running_proxysql_exporter | length == 0
...
