---
- name: Prepare payload
  ansible.builtin.set_fact:
    pmm_payload: '{{ pmm_payload_base | combine(pmm_payload_add_haproxy_base, pmm_payload_add_haproxy) }}'

- name: Add HAProxy
  ansible.builtin.include_tasks: client-api.yaml
  vars:
    pmm_service: HAProxy
  when: pmm_agent_running_haproxy_exporter | length == 0
...
