---
- name: Azure is not yet supported
  ansible.builtin.fail:
    msg: 'Support for Azure will be added soon'

- name: Prepare payload
  ansible.builtin.set_fact:
    pmm_payload: '{{ pmm_payload_base | combine(pmm_payload_add_azure_base, pmm_payload_add_azure) }}'

- name: Add Azure database
  ansible.builtin.include_tasks: client-api.yaml
  vars:
    pmm_service: AzureDatabase
  # when: pmm_agent_running_mysqld_exporter | length == 0
...
