---
- name: Prepare payload
  ansible.builtin.set_fact:
    pmm_payload: '{{ pmm_payload_base | combine(pmm_payload_add_rds_base, pmm_payload_add_rds) }}'

- name: Add RDS database
  ansible.builtin.include_tasks: client-api.yaml
  vars:
    pmm_service: RDS
  # when: pmm_agent_running_mysqld_exporter | length == 0
...
