---
# This is the entrypoint for client management and it is only
# to be used by direct calls, such as:
#
# - ansible.builtin.import_role:
#       name: pmm
#       tasks_from: client-remote
#
# This allows access to the same configuration and overrides as
# the tasks used to manage PMM server, without the need to
# toggle inclusion in the main role tasks
#

- name: Manage services
  ansible.builtin.include_tasks: 'roles/pmm/tasks/client-{{ item }}.yaml'
  when: ([item] | intersect(['azure', 'cloudsql', 'rds']))
  loop: '{{ group_names }}'
...
