---
rundeck_enabled: yes
rundeck_prune_dangling: yes

rundeck_container_name: rundeck
rundeck_container_env_file: /usr/local/percona/rundeck/env.cfg
rundeck_container_realm_file: /usr/local/percona/rundeck/realm.properties
rundeck_container_extra_args: '--ulimit=host -p 127.0.0.1:4440:4440 --volume /dev/null:/home/rundeck/etc/rundeckpro-license.key --volume {{ rundeck_container_realm_file }}:/home/rundeck/server/config/realm.properties --volume {{ rundeck_container_volume }}:/home/rundeck/server/data'
rundeck_container_image_repo: '{{ "docker.io/rundeck" }}'
rundeck_container_port: 4440
rundeck_container_volume: rundeck-data

rundeck_cli_url: "https://github.com/rundeck/rundeck-cli/releases/download/v2.0.3/rd-2.0.3.zip"
rundeck_cli_container_path: /usr/local/bin

rundeck_deploy_using: '{{ container_engine | mandatory }}'

# CHANGE DEFAULT CREDENTIALS IN OVERRIDES OR SECRET FILE BEFORE DEPLOYMENT
rundeck_manage_users:
  - username: admin
    password: admin 
    role: user,admin

rundeck_version: 4.8.0
...
