---
# It is necessary to set rundeck_admin_credentials via your inventory
# This should ideally be encrypted and use either of the following in your environment:
# - ANSIBLE_VAULT_PASSWORD_FILE=/path/to/secret
# - ANSIBLE_ASK_VAULT_PASS=1
# Other environment variables my be required, such as ANSIBLE_VAULT_IDENTITY
# Use the form username:password
# Automation will process the value as follows:
# rundeck_admin_credentials | split(":")
# if empty then fail
# else presume a username and password
rundeck_admin_credentials: "admin:admin"
rundeck_admin_set_password: true

rundeck_enabled: yes
rundeck_prune_dangling: yes

rundeck_container_env_file: /usr/local/percona/rundeck/env.cfg
rundeck_container_realm_file: /usr/local/percona/rundeck/realm.properties
rundeck_container_extra_args: '--ulimit=host -p 127.0.0.1:4440:4440 --volume /dev/null:/home/rundeck/etc/rundeckpro-license.key --volume {{ rundeck_container_realm_file }}:/home/rundeck/server/config/realm.properties --volume {{ rundeck_container_volume }}:/home/rundeck/server/data'
rundeck_container_image_repo: '{{ "docker.io/rundeck" }}'
rundeck_container_port: 4440
rundeck_container_volume: rundeck-data

rundeck_deploy_using: '{{ container_engine | mandatory }}'

rundeck_manage_users:
  - username: admin
    password: admin 
    role: user,admin

rundeck_version: 4.8.0
...
