---
rundeck_enabled: yes
rundeck_prune_dangling: yes

rundeck_container_name: rundeck
rundeck_container_env_file: /usr/local/percona/rundeck/env.cfg
rundeck_container_realm_file: /usr/local/percona/rundeck/realm.properties
rundeck_container_extra_args: '--ulimit=host -p 127.0.0.1:4440:4440 --volume /dev/null:/home/rundeck/etc/rundeckpro-license.key --volume {{ rundeck_container_realm_file }}:/home/rundeck/server/config/realm.properties --volume {{ rundeck_container_volume }}:/home/rundeck/server/data'
rundeck_container_image_repo: '{{ "docker.io/rundeck" }}'
rundeck_container_port: 4440
rundeck_container_volume: rundeck-data

rundeck_cli_tarball_name: 'rundeck-cli-{{ rundeck_cli_version }}-all.tar.xz'
rundeck_cli_filename: 'rundeck-cli-{{ rundeck_cli_version }}-all.jar'
rundeck_cli_tmp_dir: '/tmp/{{ rundeck_cli_url | basename | splitext | first }}'
rundeck_cli_user_bin_dir: '{{ ansible_env.HOME }}/bin'

rundeck_deploy_using: '{{ container_engine | mandatory }}'

# CHANGE DEFAULT CREDENTIALS IN OVERRIDES OR SECRET FILE BEFORE DEPLOYMENT
rundeck_manage_users:
  - username: admin
    password: admin 
    role: user,admin

rundeck_version: 4.8.0
rundeck_cli_version: 2.0.3
...
