---
- name: Prepare the kubectl container image
  ansible.builtin.include_role:
    name: container
  vars:
    container_image: '{{ tools_kubectl_image }}:{{ tools_kubectl_image_tag }}'

- name: Create .kube directory in user home directory
  ansible.builtin.file:
    path: "{{ tools_home_dir }}/.kube"
    state: directory
    owner: '{{ ansible_env.USER }}'
    mode: u=rwx,g=rx,o=
  tags:
    - config

- name: Check for .kube/config
  ansible.builtin.stat: 
    path: "{{ tools_kubectl_config_file }}"
  register: tools_kubectl_config_check
  tags:
    - config

- name: Include kubectl config tasks
  include_tasks: kubectl_config.yaml
  when: not tools_kubectl_config_check.stat.exists
  tags:
    - config

- name: Add alias for kubectl
  ansible.builtin.lineinfile:
    path: '{{ tools_profile_path }}'
    create: yes
    line: "alias kubectl='podman run --rm -it -v {{ tools_home_dir }}/.kube/config:/.kube/config:z --name kubectl {{ tools_kubectl_image }}:{{ tools_kubectl_image_tag }}'"
    owner: '{{ ansible_env.USER }}'
    mode: u=rw,g=r,o=
...
