---
- name: Prepare the PostgreSQL container image
  ansible.builtin.include_role:
    name: container
  vars:
    container_image: '{{ tools_postgresql_image }}:{{ tools_postgresql_image_tag }}'

- name: Add alias for PostgreSQL CLI
  ansible.builtin.lineinfile:
    path: '{{ tools_profile_path }}'
    create: yes
    line: "alias psql{{ tools_postgresql_image_tag }}='podman run --rm -it --entrypoint=psql {{ tools_postgresql_image }}:{{ tools_postgresql_image_tag }}'"
    owner: '{{ ansible_env.USER }}'
    mode: u=rw,g=r,o=
...
